### ISSUE TITLE
contwigetor is not in the npm registry

### ISSUE THREAD

**Issue by valter-silva-au** [jrm2k6/contwidgetor#2]
Hi, 
I'm trying to use this project but when I try to install it, it gives me this error:

> npm ERR! Linux 4.4.0-42-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "contwigetor"
> npm ERR! node v0.10.47
> npm ERR! npm  v2.15.1
> npm ERR! code E404
> 
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/contwigetor
> npm ERR! 404 
> npm ERR! 404 'contwigetor' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/valter/npm-debug.log

Can you please advise ?

Thank you!

**Comment by jrm2k6** [comment]
Oops sorry, there was a typo in the README. I fixed it.
Try npm install contwidgetor

**Comment by valter-silva-au** [comment]
It worked! Thank you very much @jrm2k6!
