### ISSUE TITLE
 Duplicate data property in object literal not allowed in strict mode

### ISSUE THREAD

**Issue by valter-silva-au** [jrm2k6/contwidgetor#3]
Hi, 
I'm trying your example and is given me this message:

```
valter@legion:~/git/test/contwidgetor/Example$ sudo node cli.js

/home/valter/node_modules/contwidgetor/node_modules/contwidgetor-ui/lib/ui/grid.js:88
            'color': '#aaa',
            ^^^^^^^
SyntaxError: Duplicate data property in object literal not allowed in strict mode
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/valter/node_modules/contwidgetor/node_modules/contwidgetor-ui/lib/index.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Can you please advise ?

Best regards,
Valter Henrique.

**Comment by jrm2k6** [comment]
What is your version of npm?
Did you run npm install in the example repo? and created the .env files with the right credentials?

Thanks for using it! And sorry if it is buggy I just used it myself so far, so feel free to bug me!

**Comment by jrm2k6** [comment]
It works fine for me.

I will update the README to make sure all the packages needed are installed for the Example to run. You might just have to do npm install --save webpack in the Example folder and run the webpack binary for the node_modules folder of the Example.

There is no index.html, you have to run the express server with node server.js and open localhost:5000 and you should see the example.

**Comment by valter-silva-au** [comment]
This is my npm version:

```
valter@legion:~/git/test/contwidgetor/Example$ npm --version
2.15.1
```

I'm sorry, I'm not a node.js developer, I'm following the instructions at the README.
If you could update it with the commands necessary to run your example, it would be great!

**Comment by jrm2k6** [comment]
That could be one of the reason. I am running 3.0. I can double check that later tonight after work and do all the necessary updates to the documentation. Sorry for the struggle. How important is it to have it working right now?

**Comment by valter-silva-au** [comment]
It might be @jrm2k6. Don't you worry man, I don't need right now. I was just testing your project. I would like to see my contributions from Bitbucket private repo (from my company's repo) on my GitHub profile. That's how I found your project :)

Once is updated let me know!

Good work!

**Comment by jrm2k6** [comment]
I haven't forgotten! @valterhenrique
